## Reference Data

In [1]:
%pip install pytest

Requirement already satisfied: pytest in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (9.1.0)
Requirement already satisfied: iniconfig>=1.0.1 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pytest) (2.3.0)
Requirement already satisfied: packaging>=22 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pytest) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pytest) (2.20.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
reference_data = [
  {
    "question": "What’s the leave policy?", 
    "ground_truth": "employees must submit a leave request for approval.", #Expected llm generated answer
    "context": "Employees must submit a leave request for approval. " #Expected retrieved context
  }
]

# reference_data = [
#   {
#     "question": "What is the company's policy on remote work?", 
#     "ground_truth": "Remote work is allowed up to 3 days per week.", #Expected llm generated answer
#     "context": "Remote work is allowed up to 3 days per week." #Expected retrieved context
#   }
# ]
question = reference_data[0]['question']
ground_truth = reference_data[0]['ground_truth']
context = reference_data[0]['context']
print (f"question: {question}")
print (f"ground_truth: {ground_truth}")
print (f"context: {context}")

question: What’s the leave policy?
ground_truth: employees must submit a leave request for approval.
context: Employees must submit a leave request for approval.

In [3]:
# Retrieve context from Milvus DB

from milvus_chatbot_with_rag import retrieve_similiar_contexts, generate_answer

def perform_retrieval(question):

    retrieved_context = retrieve_similiar_contexts(question, "policy_docs_collection", 1)[0]['content']
    print (f"perform_retrieval.retrieved_context: {retrieved_context}")
    return retrieved_context

# Generate answer using LLM

question = reference_data[0]['question']
context = perform_retrieval(question)
answer = generate_answer(question, context)
answer

/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/Session12_ragas_eval/milvus_chatbot_with_rag.py:28: PyMilvusDeprecationWarning: `connections.connect` is an ORM-style PyMilvus API and will be removed in PyMilvus 3.1. Use `MilvusClient` instead.
  connections.connect(

Connected to Milvus on Zilliz Cloud

/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/Session12_ragas_eval/milvus_chatbot_with_rag.py:36: PyMilvusDeprecationWarning: `Collection` is an ORM-style PyMilvus API and will be removed in PyMilvus 3.1. Use `MilvusClient` instead.
  collection = Collection(collection_name)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
I0617 16:50:16.623178 1004267 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(92, generation: 1)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7359.31it/s]
/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/Session12_ragas_eval/milvus_chatbot_with_rag.py:41: PyMilvusDeprecationWarning: `Collection.search` is an ORM-style PyMilvus API and will be removed in PyMilvus 3.1. Use `MilvusClient` instead.
  results = collection.search(

perform_retrieval.retrieved_context: Employees must submit a leave request for approval.

'Employees must submit a leave request for approval.'

In [4]:
%pip install ragas datasets

I0617 16:50:25.038432 1004620 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(92, generation: 1)

Requirement already satisfied: ragas in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (0.4.3)
Requirement already satisfied: datasets in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (5.0.0)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (2.4.5)
Requirement already satisfied: tiktoken in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.13.0)
Requirement already satisfied: pydantic>=2.0.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (2.13.3)
Requirement already satisfied: nest-asyncio in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (1.6.0)
Requirement already satisfied: appdirs in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (5.6.3)
Requirement already satisfied: typer in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.25.1)
Requirement already satisfied: rich in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (14.3.4)
Requirement already satisfied: openai>=1.0.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (2.33.0)
Requirement already satisfied: tqdm in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (4.67.3)
Requirement already satisfied: instructor in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (1.15.3)
Requirement already satisfied: pillow>=10.4.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (12.2.0)
Requirement already satisfied: networkx in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (3.6.1)
Requirement already satisfied: scikit-network in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.33.5)
Requirement already satisfied: langchain in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.3.25)
Requirement already satisfied: langchain-core in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.3.86)
Requirement already satisfied: langchain-community in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.3.24)
Requirement already satisfied: langchain_openai in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from ragas) (0.3.35)
Requirement already satisfied: filelock in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (3.0.3)
Requirement already satisfied: requests>=2.32.2 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (1.15.0)
Requirement already satisfied: packaging in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from openai>=1.0.0->ragas) (0.14.0)
Requirement already satisfied: sniffio in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pydantic>=2.0.0->ragas) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pydantic>=2.0.0->ragas) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: click>=8.2.1 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from typer->ragas) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from typer->ragas) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from rich->ragas) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from rich->ragas) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from instructor->ragas) (0.18.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from instructor->ragas) (3.1.6)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from instructor->ragas) (9.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain->ragas) (0.3.8)
Requirement already satisfied: langsmith<0.4,>=0.1.17 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain->ragas) (0.3.45)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain->ragas) (2.0.50)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain-core->ragas) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.1.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.17->langchain->ragas) (3.11.9)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.17->langchain->ragas) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.17->langchain->ragas) (0.23.0)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain-community->ragas) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain-community->ragas) (2.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (0.9.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain-community->ragas) (1.2.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community->ragas) (1.1.0)
Requirement already satisfied: regex in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from tiktoken->ragas) (2026.5.9)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: scipy>=1.7.3 in /Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/.venv/lib/python3.13/site-packages (from scikit-network->ragas) (1.17.1)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import faithfulness, answer_correctness

from dotenv import load_dotenv
from openai import OpenAI
import os

# --- Load API Key ---
load_dotenv(override=True, dotenv_path="../.env")
my_api_key = os.getenv("OPENAI_API_KEY")


client = OpenAI(api_key=my_api_key)

# Question User asked
question = reference_data[0]['question']

# Reference context (should be a string)
reference_context = reference_data[0]['context']

# ground truth answer
ground_truth = reference_data[0]['ground_truth']

# Retrieved context (a string from perform_retrieval)
retrieved_context = [perform_retrieval(question)]
llm_answer = generate_answer(question, retrieved_context[0])

# Build dataset properly
dataset_dict = {
    "question": [question],
    "contexts": [retrieved_context],    # list of strings INSIDE another list
    "ground_truth": [ground_truth],   # single string/ reference answer
    "answer": [llm_answer]
}

print(f"dataset_dict: {dataset_dict}")

ragas_dataset = Dataset.from_dict(dataset_dict)

/var/folders/b8/45pl36ms0xx399j715gybz840000gn/T/ipykernel_4996/3037382094.py:3: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import faithfulness, answer_correctness
/var/folders/b8/45pl36ms0xx399j715gybz840000gn/T/ipykernel_4996/3037382094.py:3: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import faithfulness, answer_correctness
/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/Session12_ragas_eval/milvus_chatbot_with_rag.py:28: PyMilvusDeprecationWarning: `connections.connect` is an ORM-style PyMilvus API and will be removed in PyMilvus 3.1. Use `MilvusClient` instead.
  connections.connect(

Connected to Milvus on Zilliz Cloud

/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/Session12_ragas_eval/milvus_chatbot_with_rag.py:36: PyMilvusDeprecationWarning: `Collection` is an ORM-style PyMilvus API and will be removed in PyMilvus 3.1. Use `MilvusClient` instead.
  collection = Collection(collection_name)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6362.21it/s]
/Users/amiteshsinha/Training/ai_labs/2026_4_genAI_Lab/Session12_ragas_eval/milvus_chatbot_with_rag.py:41: PyMilvusDeprecationWarning: `Collection.search` is an ORM-style PyMilvus API and will be removed in PyMilvus 3.1. Use `MilvusClient` instead.
  results = collection.search(

perform_retrieval.retrieved_context: Employees must submit a leave request for approval.
dataset_dict: {'question': ['What’s the leave policy?'], 'contexts': [['Employees must submit a leave request for approval.']], 'ground_truth': ['employees must submit a leave request for approval.'], 'answer': ['Employees must submit a leave request for approval.']}

In [6]:
from ragas.llms.base import llm_factory
from ragas import evaluate
from ragas.metrics import answer_correctness

results = evaluate(
    dataset=ragas_dataset,
    metrics=[faithfulness, answer_correctness]  
)


print("LLM Generation Evaluation Results:")
results.to_pandas()

/var/folders/b8/45pl36ms0xx399j715gybz840000gn/T/ipykernel_4996/84979105.py:3: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import answer_correctness
I0617 16:50:38.433135 1005256 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(92, generation: 1)
Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]Exception raised in Job[1]: TypeError(Cannot use aembed_text() with a synchronous client. Use embed_text() instead.)
Evaluating: 100%|██████████| 2/2 [00:10<00:00,  5.04s/it]

LLM Generation Evaluation Results:

,user_input,retrieved_contexts,response,reference,faithfulness,answer_correctness
0,What’s the leave policy?,[Employees must submit a leave request for app...,Employees must submit a leave request for appr...,employees must submit a leave request for appr...,1.0,NaN

In [7]:
from ragas.llms.base import llm_factory
from ragas import evaluate
from ragas.metrics import answer_correctness

# Create the modern LLM wrapper
client = OpenAI()
llm = llm_factory("gpt-4o-mini", client=client)

# Run evaluation
results = evaluate(
    dataset=ragas_dataset,
    metrics=[answer_correctness],
    llm=llm
)

print("LLM Generation Evaluation Results:")
results.to_pandas()

/var/folders/b8/45pl36ms0xx399j715gybz840000gn/T/ipykernel_4996/3714285956.py:3: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import answer_correctness
Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]Exception raised in Job[0]: TypeError(Cannot use aembed_text() with a synchronous client. Use embed_text() instead.)
Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.61s/it]

LLM Generation Evaluation Results:

,user_input,retrieved_contexts,response,reference,answer_correctness
0,What’s the leave policy?,[Employees must submit a leave request for app...,Employees must submit a leave request for appr...,employees must submit a leave request for appr...,NaN

##